"""Add Feature Set B cells to h1_clustering.ipynb"""
import json, pathlib

NB_PATH = pathlib.Path(__file__).resolve().parent.parent / "h1_clustering" / "h1_clustering.ipynb"

with open(NB_PATH, encoding="utf-8") as f:
    nb = json.load(f)

def md_cell(cid, lines):
    return {"cell_type": "markdown", "source": lines, "metadata": {"id": cid}}

def code_cell(cid, lines):
    return {"cell_type": "code", "source": lines, "metadata": {"id": cid},
            "execution_count": None, "outputs": []}

NEW_CELLS = [
    md_cell("md-fs-b-header", [
        "---\n",
        "\n",
        "## Feature Set B — 단기 시그널 실험 (recent3/6: 전투력 · 어센틱심볼 · 헥사조각)\n",
        "\n",
        "**목적:** 12개월 평균 피처 없이 단기(3/6개월) 시그널 3종만으로 파킹 탐지 가능 여부 검증.\n",
        "\n",
        "| 피처 | 설명 |\n",
        "|---|---|\n",
        "| `recent{3,6}_delta_combat_power` | 월평균 전투력 변화량 (winsorize P5–P95) |\n",
        "| `recent{3,6}_delta_authentic_symbol` | 어센틱 심볼 증감 (≥0 클램핑) |\n",
        "| `recent{3,6}_delta_hexa_frag` | 헥사 강화 조각 소비 변화량 (`hexa_fragments.csv`) |\n",
        "\n",
        "> 아케인 심볼·레벨·유니온 제거 — 3개 피처로도 파킹 시그널 포착 여부 확인.\n",
    ]),

    code_cell("fs-b-prep", [
        "# Feature Set B — 데이터 준비 (hexa_fragments.csv 병합)\n",
        "hf = pd.read_csv('../data/hexa_fragments.csv', encoding='utf-8-sig',\n",
        "                 usecols=['ocid', 'avg_monthly_delta_hexa_frag',\n",
        "                          'recent3_delta_hexa_frag', 'recent6_delta_hexa_frag'])\n",
        "\n",
        "df_b = df_final.merge(hf, on='ocid', how='left').reset_index(drop=True)\n",
        "\n",
        "# ── B3 피처 엔지니어링 ──────────────────────────────────────────────────────\n",
        "df_b['b3_delta_cp'] = np.array(\n",
        "    winsorize(\n",
        "        df_b['recent3_delta_combat_power'].fillna(df_b['delta_cp_winsor']),\n",
        "        limits=[0.05, 0.05]\n",
        "    )\n",
        ")\n",
        "df_b['b3_delta_auth'] = (\n",
        "    df_b['recent3_delta_authentic_symbol']\n",
        "    .fillna(df_b['avg_monthly_delta_authentic_symbol'])\n",
        "    .clip(lower=0)\n",
        ")\n",
        "df_b['b3_delta_hfrag'] = (\n",
        "    df_b['recent3_delta_hexa_frag']\n",
        "    .fillna(df_b['avg_monthly_delta_hexa_frag'])\n",
        "    .clip(lower=0)\n",
        ")\n",
        "\n",
        "# ── B6 피처 엔지니어링 ──────────────────────────────────────────────────────\n",
        "df_b['b6_delta_cp'] = np.array(\n",
        "    winsorize(\n",
        "        df_b['recent6_delta_combat_power'].fillna(df_b['delta_cp_winsor']),\n",
        "        limits=[0.05, 0.05]\n",
        "    )\n",
        ")\n",
        "df_b['b6_delta_auth'] = (\n",
        "    df_b['recent6_delta_authentic_symbol']\n",
        "    .fillna(df_b['avg_monthly_delta_authentic_symbol'])\n",
        "    .clip(lower=0)\n",
        ")\n",
        "df_b['b6_delta_hfrag'] = (\n",
        "    df_b['recent6_delta_hexa_frag']\n",
        "    .fillna(df_b['avg_monthly_delta_hexa_frag'])\n",
        "    .clip(lower=0)\n",
        ")\n",
        "\n",
        "FS_B3 = ['b3_delta_cp', 'b3_delta_auth', 'b3_delta_hfrag']\n",
        "FS_B6 = ['b6_delta_cp', 'b6_delta_auth', 'b6_delta_hfrag']\n",
        "\n",
        "df_B3_data = df_b[FS_B3].dropna()\n",
        "df_B6_data = df_b[FS_B6].dropna()\n",
        "idx_B3 = df_B3_data.index\n",
        "idx_B6 = df_B6_data.index\n",
        "\n",
        "X_B3 = StandardScaler().fit_transform(df_B3_data.values)\n",
        "X_B6 = StandardScaler().fit_transform(df_B6_data.values)\n",
        "\n",
        "print(f'Feature Set B3 (recent3) 샘플: {len(X_B3):,}명')\n",
        "print(f'Feature Set B6 (recent6) 샘플: {len(X_B6):,}명')\n",
        "print(f'\\nhexa_frag NaN 비율:')\n",
        "print(f'  recent3_delta_hexa_frag : {df_b[\"recent3_delta_hexa_frag\"].isna().mean():.1%}')\n",
        "print(f'  recent6_delta_hexa_frag : {df_b[\"recent6_delta_hexa_frag\"].isna().mean():.1%}')\n",
        "print(f'\\nb3_delta_hfrag 분포:')\n",
        "print(df_b['b3_delta_hfrag'].describe().round(1).to_string())\n",
    ]),

    code_cell("fs-b-kmeans", [
        "# Feature Set B — K-Means k=2~8 Silhouette 비교\n",
        "\n",
        "ks_b = list(range(2, 9))\n",
        "sils_B3, sils_B6 = [], []\n",
        "\n",
        "for k in ks_b:\n",
        "    sils_B3.append(silhouette_score(X_B3,\n",
        "        KMeans(n_clusters=k, n_init=20, random_state=42).fit_predict(X_B3)))\n",
        "    sils_B6.append(silhouette_score(X_B6,\n",
        "        KMeans(n_clusters=k, n_init=20, random_state=42).fit_predict(X_B6)))\n",
        "\n",
        "best_k_B3   = ks_b[int(np.argmax(sils_B3))]\n",
        "best_k_B6   = ks_b[int(np.argmax(sils_B6))]\n",
        "best_sil_B3 = max(sils_B3)\n",
        "best_sil_B6 = max(sils_B6)\n",
        "\n",
        "# 전체 비교표\n",
        "_Ap_col = sils_Ap if has_recent6 else [None] * len(ks_b)\n",
        "comp_b = pd.DataFrame({\n",
        "    'k'            : ks_b,\n",
        "    'A  (12mo/5f)' : silhouettes,\n",
        "    \"A' (r6  /5f)\" : _Ap_col,\n",
        "    'B3 (r3  /3f)' : sils_B3,\n",
        "    'B6 (r6  /3f)' : sils_B6,\n",
        "}).set_index('k').round(4)\n",
        "\n",
        "print('── Silhouette 비교: A / A\\' / B3 / B6 ────────────────────────────────')\n",
        "print(comp_b.to_string())\n",
        "print(f'\\nB3 best: k={best_k_B3}, sil={best_sil_B3:.4f}')\n",
        "print(f'B6 best: k={best_k_B6}, sil={best_sil_B6:.4f}')\n",
        "\n",
        "# 비교 플롯\n",
        "fig, ax = plt.subplots(figsize=(11, 5))\n",
        "ax.plot(ks_b, silhouettes, 's-',  color='steelblue',   label='A  (12mo avg, 5f)',     linewidth=2)\n",
        "if has_recent6:\n",
        "    ax.plot(ks_b, sils_Ap, 'o--', color='darkorange',  label=\"A' (recent6,  5f)\",    linewidth=2)\n",
        "ax.plot(ks_b, sils_B3,  '^-',  color='forestgreen',  label='B3 (recent3: CP·Auth·Hfrag)', linewidth=2)\n",
        "ax.plot(ks_b, sils_B6,  'D--', color='purple',        label='B6 (recent6: CP·Auth·Hfrag)', linewidth=2)\n",
        "ax.axvline(best_k_B3, linestyle=':', color='forestgreen', alpha=0.5)\n",
        "ax.axvline(best_k_B6, linestyle=':', color='purple',      alpha=0.5)\n",
        "ax.set_xlabel('k'); ax.set_ylabel('Silhouette Score')\n",
        "ax.set_title(\"Feature Set 비교: K-Means Silhouette (A / A' / B3 / B6)\")\n",
        "ax.set_xticks(ks_b); ax.legend()\n",
        "plt.tight_layout()\n",
        "plt.savefig('figures/06_silhouette_compare_all.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
    ]),

    code_cell("fs-b-profile", [
        "# Feature Set B — 최적 모델 프로파일링\n",
        "\n",
        "# B3 vs B6 중 더 높은 silhouette 사용\n",
        "if best_sil_B3 >= best_sil_B6:\n",
        "    best_X_B, best_idx_B, best_k_B, best_FS_B, best_sil_B, best_tag_B = \\\n",
        "        X_B3, idx_B3, best_k_B3, FS_B3, best_sil_B3, 'B3 (recent3)'\n",
        "else:\n",
        "    best_X_B, best_idx_B, best_k_B, best_FS_B, best_sil_B, best_tag_B = \\\n",
        "        X_B6, idx_B6, best_k_B6, FS_B6, best_sil_B6, 'B6 (recent6)'\n",
        "\n",
        "km_B_best = KMeans(n_clusters=best_k_B, n_init=20, random_state=42)\n",
        "df_b.loc[best_idx_B, 'cluster_km_B'] = km_B_best.fit_predict(best_X_B)\n",
        "\n",
        "profile_B = df_b.loc[best_idx_B].groupby('cluster_km_B')[\n",
        "    best_FS_B + ['stagnation_score']\n",
        "].mean()\n",
        "profile_B['n'] = df_b.loc[best_idx_B].groupby('cluster_km_B').size()\n",
        "\n",
        "# 파킹 클러스터 = 전투력 변화량 평균 최소\n",
        "parking_col_B   = best_FS_B[0]  # b3_delta_cp or b6_delta_cp\n",
        "parking_cl_B_id = int(profile_B[parking_col_B].idxmin())\n",
        "\n",
        "profile_B['is_parking'] = (profile_B.index == parking_cl_B_id).astype(int)\n",
        "profile_B['parked_proxy_%'] = (\n",
        "    df_b.loc[best_idx_B].groupby('cluster_km_B')\n",
        "    .apply(lambda g: (g['avg_monthly_delta_level'] <= 0.1).mean() * 100)\n",
        ")\n",
        "\n",
        "df_b['is_parking_B'] = np.nan\n",
        "df_b.loc[best_idx_B, 'is_parking_B'] = (\n",
        "    df_b.loc[best_idx_B, 'cluster_km_B'] == parking_cl_B_id\n",
        ").astype(int)\n",
        "\n",
        "n_parking_B  = int(df_b['is_parking_B'].sum())\n",
        "stag5_all_B  = int((df_b['stagnation_score'] == 5).sum())\n",
        "stag5_in_B   = int((df_b.loc[df_b['is_parking_B'] == 1, 'stagnation_score'] == 5).sum())\n",
        "\n",
        "print(f'=== {best_tag_B} 클러스터링 (k={best_k_B}, sil={best_sil_B:.4f}) ===')\n",
        "print(f'파킹 클러스터 ID = {parking_cl_B_id}')\n",
        "display(profile_B.round(2))\n",
        "print(f'\\n파킹 클러스터 : {n_parking_B}명 ({n_parking_B / len(df_b):.1%})')\n",
        "print(f'stagnation=5  : {stag5_in_B}/{stag5_all_B}명 ({stag5_in_B / max(stag5_all_B,1)*100:.1f}%)')\n",
        "\n",
        "# level_bin 분포\n",
        "print('\\n레벨 밴드 분포 (클러스터 x level_bin, 행 비율 %):')\n",
        "lb_dist_B = pd.crosstab(\n",
        "    df_b.loc[best_idx_B, 'cluster_km_B'],\n",
        "    df_b.loc[best_idx_B, 'level_bin'],\n",
        "    normalize='index'\n",
        ").round(3) * 100\n",
        "display(lb_dist_B)\n",
    ]),

    code_cell("fs-b-pca", [
        "# Feature Set B — PCA 2D 시각화\n",
        "\n",
        "pca_B      = PCA(n_components=2, random_state=42)\n",
        "X_B_pca    = pca_B.fit_transform(best_X_B)\n",
        "\n",
        "pca_B_df = pd.DataFrame(X_B_pca, columns=['PC1', 'PC2'], index=best_idx_B)\n",
        "pca_B_df = pca_B_df.join(df_b[['cluster_km_B', 'stagnation_score', 'level_bin']])\n",
        "pca_B_df['is_parking_B'] = (pca_B_df['cluster_km_B'] == parking_cl_B_id).astype(int)\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "for val, (color, lbl) in enumerate(zip(['#aec6cf', '#e15759'], ['비파킹', '파킹'])):\n",
        "    mask = pca_B_df['is_parking_B'] == val\n",
        "    axes[0].scatter(pca_B_df.loc[mask, 'PC1'], pca_B_df.loc[mask, 'PC2'],\n",
        "                    s=8, alpha=0.5, color=color, label=lbl)\n",
        "axes[0].set_title(f'{best_tag_B}: 파킹/비파킹')\n",
        "axes[0].set_xlabel('PC1'); axes[0].set_ylabel('PC2')\n",
        "axes[0].legend(markerscale=2)\n",
        "\n",
        "sc = axes[1].scatter(pca_B_df['PC1'], pca_B_df['PC2'],\n",
        "                     c=pca_B_df['stagnation_score'], cmap='Reds',\n",
        "                     s=8, alpha=0.6, vmin=0, vmax=5)\n",
        "plt.colorbar(sc, ax=axes[1], label='stagnation_score')\n",
        "axes[1].set_title(f'{best_tag_B}: stagnation_score')\n",
        "axes[1].set_xlabel('PC1'); axes[1].set_ylabel('PC2')\n",
        "\n",
        "ev_B = pca_B.explained_variance_ratio_\n",
        "plt.suptitle(f'PCA 2D — {best_tag_B}  |  PC1={ev_B[0]:.1%}, PC2={ev_B[1]:.1%}', y=1.02)\n",
        "plt.tight_layout()\n",
        "plt.savefig('figures/07_pca_fsB.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
    ]),

    code_cell("fs-b-summary", [
        "# Feature Set B — H1 판정 요약\n",
        "\n",
        "print('=' * 60)\n",
        "print('  Feature Set B 실험 요약')\n",
        "print('=' * 60)\n",
        "print(f'  피처 ({best_tag_B}): {best_FS_B}')\n",
        "print(f'  best k: {best_k_B},  Silhouette = {best_sil_B:.4f}')\n",
        "\n",
        "verdict_B = '분리 가능 (H1 지지)' if best_sil_B > 0.3 else '약한 분리 (H1 조건부 지지)'\n",
        "print(f'  판정  : {verdict_B}')\n",
        "print(f'  파킹 클러스터: {n_parking_B}명 ({n_parking_B / len(df_b):.1%})')\n",
        "print(f'  stagnation=5 집중: {stag5_in_B}/{stag5_all_B}명 ({stag5_in_B / max(stag5_all_B,1)*100:.1f}%)')\n",
        "print()\n",
        "print('  ── Feature Set 비교 (Silhouette) ──────────────────────')\n",
        "print(f'  A  (12mo avg, 5 피처) : {best_sil:.4f}  (k={best_k})')\n",
        "if has_recent6:\n",
        "    print(f\"  A' (recent6,  5 피처) : {best_sil_Ap:.4f}  (k={best_k_Ap})\")\n",
        "print(f'  B3 (recent3,  3 피처) : {best_sil_B3:.4f}  (k={best_k_B3})')\n",
        "print(f'  B6 (recent6,  3 피처) : {best_sil_B6:.4f}  (k={best_k_B6})')\n",
    ]),
]

# 기존 cell ID 중복 확인 후 추가
existing_ids = {c.get("metadata", {}).get("id") for c in nb["cells"]}
for cell in NEW_CELLS:
    cid = cell["metadata"]["id"]
    if cid in existing_ids:
        print(f"  SKIP (already exists): {cid}")
    else:
        nb["cells"].append(cell)
        print(f"  ADDED: {cid}")

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"\nSaved: {NB_PATH}")
print(f"Total cells: {len(nb['cells'])}")
